2025-08-15 18:05:51,577 - INFO - ============================================================
2025-08-15 18:05:51,671 - INFO - ============================================================
2025-08-15 18:05:51,738 - ERROR - Code sortie: 1
2025-08-15 18:05:51,738 - ERROR - Erreur:
Traceback (most recent call last):
  File "C:\ENSI\2éme année\Stage ii2\essai\test\multi_scraper.py", line 5, in <module>
    from scraping.scraper_dynamic import scrape_dynamic_site
  File "C:\ENSI\2éme année\Stage ii2\essai\test\scraping\scraper_dynamic.py", line 8, in <module>
    from selenium.common.exceptions import (
ModuleNotFoundError: No module named 'selenium'

